## Security Configuration
security:
    encoders:
        Ewave\CoreBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: EwaveCoreBundle:User, property: email }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
    access_control:

        - { path: /control/setting, roles: ROLE_ADMIN }
        - { path: /control/user, roles: [ROLE_MANAGER,ROLE_TL,ROLE_EEG,ROLE_SA] }
        - { path: /control.*, roles: [ROLE_USER,ROLE_BA,ROLE_DEV,ROLE_DEV_ROSTER,ROLE_SUP]}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER,ROLE_TL,ROLE_EEG,ROLE_SA]
        ROLE_MANAGER: [ROLE_USER,ROLE_BA,ROLE_DEV,ROLE_DEV_ROSTER,ROLE_SUP]
        ROLE_TL: [ROLE_USER,ROLE_BA,ROLE_DEV,ROLE_DEV_ROSTER,ROLE_SUP]
        ROLE_EEG: [ROLE_USER,ROLE_BA,ROLE_DEV,ROLE_DEV_ROSTER,ROLE_SUP]
        ROLE_SA: [ROLE_USER,ROLE_BA,ROLE_DEV,ROLE_DEV_ROSTER,ROLE_SUP]
