<?php

namespace Vilka\CoreBundle\Repository;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountByPlatform($platform)
    {
        $query = $this->createQueryBuilder('c')
            ->select('COUNT(c)');
        $query->where('c.platform = :platform')
            ->setParameter('platform', $platform);

        return $query->getQuery()->getSingleScalarResult();
    }
}
