<?php

namespace Vilka\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitchenRepository extends EntityRepository
{

}
