<?php

namespace Vilka\CoreBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPlatform($platform) {
        $query = $this->createQueryBuilder('l')
            ->select('l')
            ->where('l.platform = :platform')
            ->setParameter('platform', $platform)
        ;

        return $query->getQuery()->getArrayResult();
    }
}
