ewave_core_homepage:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
ewave_control:
    resource: "@EwaveCoreBundle/Controller/AdminController.php"
    type:     annotation
ewave_control_setting:
    resource: "@EwaveCoreBundle/Controller/SettingController.php"
    type:     annotation
ewave_control_user:
    resource: "@EwaveCoreBundle/Controller/UserController.php"
    type:     annotation
ewave_control_history:
    resource: "@EwaveCoreBundle/Controller/HistoryController.php"
    type:     annotation
ewave_control_team:
    resource: "@EwaveCoreBundle/Controller/TeamController.php"
    type:     annotation
ewave_control_project:
    resource: "@EwaveCoreBundle/Controller/ProjectController.php"
    type:     annotation
ewave_control_environment:
    resource: "@EwaveCoreBundle/Controller/EnvironmentController.php"
    type:     annotation
ewave_control_ssh:
    resource: "@EwaveCoreBundle/Controller/SshController.php"
    type:     annotation
ewave_control_mysql:
    resource: "@EwaveCoreBundle/Controller/MysqlController.php"
    type:     annotation

_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout