parameters:
    ewave.manager.subway.class: Ewave\CoreBundle\Manager\SubwayManager

services:
  twig.extension.decode:
          class: Ewave\CoreBundle\Twig\DecodeExtension
          public: true
          tags:
              - { name: twig.extension }