<?php

namespace Ewave\CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * EnvironmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentRepository extends EntityRepository
{
    public function getAllByProject($project)
    {
        $query = $this->createQueryBuilder('s');
        $query->where('s.project = :id')
            ->setParameter('id', $project);
        $query = $query->getQuery();

        return $query->getResult();
    }
}
