<?php

namespace Ewave\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    public function getAll()
    {
        $query = $this->createQueryBuilder('f')
            ->addSelect('f');

        return $query->getQuery()->getResult();
    }
}
