<?php

namespace Ewave\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    public function getList(
        $userId,
        $search,
        $page = 1,
        $limit = 20
    ) {
        $query = $this->createQueryBuilder('s')
            ->addSelect('s')
            ->leftJoin('s.user', 'u', array('u.username', 'u.id'))
        ;
        $order = isset($_COOKIE['sort_table']) ? explode(' ', $_COOKIE['sort_table']) : array('id', 'desc');
        $this->setFilters($userId, $query, $search);
        $query = $query->setMaxResults($limit)
            ->setFirstResult(($page - 1) * $limit)
            ->orderBy('s.'.$order[0], strtoupper($order[1]))
            ->getQuery();

        return $query->getResult();
    }

    public function getListPages(
        $userId,
        $search,
        $limit = 20
    ) {
        $query = $this->createQueryBuilder('s')
            ->select('COUNT(s)')
            ->leftJoin('s.user', 'u', array('u.username', 'u.id'))
        ;
        $this->setFilters($userId, $query, $search);
        $pager['limit'] = $limit;
        $pager['count'] = $query->getQuery()->getSingleScalarResult();
        return $pager;
    }

    private function setFilters($userId, &$query, $search)
    {
        if ($userId) {
            $query = $query->where('u.id LIKE :uid')
                ->setParameter('uid', '%' . $userId . '%');
        }
        if ($search) {
            $query = $query->andWhere('s.date LIKE :date')
                ->setParameter('date', '%' . $search . '%');
            $query = $query->orWhere('s.cols LIKE :cols')
                ->setParameter('cols', '%' . $search . '%');
            $query = $query->orWhere('s.params LIKE :params')
                ->setParameter('params', '%' . $search . '%');
            $query = $query->orWhere('u.username LIKE :username')
                ->setParameter('username', '%' . $search . '%');
        }
    }
}
