<?php

namespace Ewave\CoreBundle\Repository;

/**
 * HtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtaRepository extends \Doctrine\ORM\EntityRepository
{
}
