<?php

namespace Ewave\CoreBundle\Repository;

/**
 * MysqlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MysqlRepository extends \Doctrine\ORM\EntityRepository
{
}
