<?php

namespace Ewave\CoreBundle\Repository;

/**
 * SshRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SshRepository extends \Doctrine\ORM\EntityRepository
{
}
