<?php

namespace Ewave\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function getList(
        $search,
        $page = 1,
        $limit = 20
    ) {
        $query = $this->createQueryBuilder('s')
            ->addSelect('s');
        $order = isset($_COOKIE['sort_table']) ? explode(' ', $_COOKIE['sort_table']) : array('id', 'desc');
        $this->setFilters($query, $search);
        $query = $query->setMaxResults($limit)
            ->setFirstResult(($page - 1) * $limit)
            ->orderBy('s.'.$order[0], strtoupper($order[1]))
            ->getQuery();
        return $query->getResult();
    }

    public function getListPages(
        $search,
        $limit = 20
    ) {
        $query = $this->createQueryBuilder('s')
            ->select('COUNT(s)');
        $this->setFilters($query, $search);
        $pager['limit'] = $limit;
        $pager['count'] = $query->getQuery()->getSingleScalarResult();
        return $pager;
    }

    private function setFilters(&$query, $search)
    {
        if ($search) {
            $query = $query->where('s.title LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }
    }

    public function getAll()
    {
        $query = $this->createQueryBuilder('s')
            ->addSelect('s.id, s.title');
        $query = $query->orderBy('s.title')
            ->getQuery();
        return $query->getResult();
    }
}
