<?php

namespace Vilka\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SettingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Vilka\CoreBundle\Controller\SettingController();
        return $instance;
    }
}
